name: ğŸš€ Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        axon-framework:
          - version: 5.0.0-preview
          - version: 5.0.0-SNAPSHOT
      fail-fast: false

    steps:
      - name: ğŸ›ï¸ Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ”§ Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version-file: .java-version
          distribution: 'zulu'
          cache: maven

      - name: ğŸ“¦ Build with Maven
        run: mvn -B compile -ntp -B -Daxon.version=${{ matrix.axon-framework.version }}

      - name: ğŸ§ª Run tests
        run: mvn -B test -ntp -B
